### ISSUE TITLE
[Todo][Feature] Typescript support

### ISSUE THREAD

**Issue by bahung1221** [bahung1221/cache-all#2]

**Comment by FFKL** [comment]
What about typescript? Do you want to use only type-definition file, or full rewriting (v3.0.0)?

**Comment by bahung1221** [comment]
Good morning bro,

I think full rewriting will take time, but i still want to have it in v3.0.0. So is it a good decision if we add type-definition files just for now? I think it will be a great step to support typescript.

v3 maybe will be start in the next year, because i have too much tasks in my personal job at this time 🤣
In v3 i think i want to add some features like `events` and `automate clear cache` (example clear cache when cached size reached to 200MB). And i think about **modular cache module** to separate package, it will independency.

So for now, do you think we should add type-definition files? And may you help me to create PR for it?

Thank you so much

**Comment by FFKL** [comment]
Hello! I think, we can implement basic types now. I'll try)

**Comment by bahung1221** [comment]
Hi bro,
It was release as `v2.1.0`. Of course, it worked like a charm. Thank you so much 😄
