### ISSUE TITLE
Can't resolve 'hiredis'

### ISSUE THREAD

**Issue by AlexanderAllen** [bahung1221/cache-all#20]
Getting a compilation error, using `"cache-all": "^2.0.7"`:

```
ERROR in ./node_modules/redis-parser/lib/hiredis.js
Module not found: Error: Can't resolve 'hiredis' in '.../node_modules/redis-parser/lib'
 @ ./node_modules/redis-parser/lib/hiredis.js 3:14-32
 @ ./node_modules/redis-parser/lib/parser.js
 @ ./node_modules/redis-parser/index.js
 @ ./node_modules/redis/index.js
 @ ./node_modules/cache-all/src/core/redis.js
 @ ./node_modules/cache-all/src/cache.js
 @ ./node_modules/cache-all/memory.js
 @ ./src/containers/Workbench.jsx
 @ ./src/containers/AppContainer.jsx
 @ ./src/renderer/index.js
 @ multi react-hot-loader/patch ./src/renderer/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
       1 module
```

**Comment by AlexanderAllen** [comment]
I think I resolved it by doing:
```
bash3.2> yarn add hiredis
```

**Comment by bahung1221** [comment]
Hi @AlexanderAllen,

It seems a dependency problem of [redis package](https://github.com/NodeRedis/node_redis/blob/master/package.json#L30),
as you see, redis has [redis-parser](https://github.com/NodeRedis/node-redis-parser/blob/master/package.json#L42) as dependency, but redis-parser just add hiredis as an **devDependency**

I will investigate it and add hiredis to my dependency if needed,
Thank you so much

**Comment by bahung1221** [comment]
It seems we must add hiredis as an peer-dependency https://github.com/NodeRedis/node-redis-parser/pull/36, lol

**Comment by bahung1221** [comment]
Hi @AlexanderAllen ,
I added hiredis as a dependency in v2.0.8.

Thank you very much 😄
