### ISSUE TITLE
Flutter:  cache-sksl not working on iOS (TestFlight)

### ISSUE THREAD

**Issue by paintingStyle** [bahung1221/cache-all#25]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/22866404/147640213-b94a5db0-fe30-4996-b271-a2ce2ca85c62.png">

Sorry to disturb you, I saw your flutter issues

I used flutter build ios to generate .ipa

```
flutter build ios --release --bundle-sksl-path flutter_01.sksl.json
```

I can’t upload to TestFlight, he reported an error, I uploaded it directly using Xcode, and it succeeded

 Error: code 1176 (App Store operation failed. Unable to process application at this time due to the following error: Invalid Provisioning Profile. The provisioning profile included in the bundle com.mhh.xxx [Payload/Runner.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal..)

<img width="831" alt="image" src="https://user-images.githubusercontent.com/22866404/147640628-71be524f-b509-44fa-a99a-c649974c20df.png">

How did you upload it successfully?

thanks

**Comment by bahung1221** [comment]
Hi @paintingStyle ,

It seems a provisioning problem, which is related to your Apple Developer account, you need the correct provisioning profile to sign the bundle before you can upload it to Testflight/AppStore.

Maybe you don't have one or maybe you registered the wrong `certificate/provisioning` type.

The below stackoverflow issues may help:
- https://stackoverflow.com/questions/19697237/invalid-provisioning-profile-missing-code-signing-certificate
- https://stackoverflow.com/questions/34096279/which-certificate-type-and-provisioning-profile-type-should-i-use-for-test-fligh
