### ISSUE TITLE
How to update the cache when edit data?

### ISSUE THREAD

**Issue by vibav** [bahung1221/cache-all#5]
I ran into a problem that when editing data, old data that is stored in the cache does not update the changes until the cache expires. How to do caching when changing data?

routing:

```
const express = require("express");
const router = express.Router();
const controller = require("../controllers/users");
const cache = require('cache-all')

router.get("/get_all", cache.middleware(86400), controller.getAll);
router.patch("/patch/:USER_ID", controller.update);

module.exports = router;

```

controller:

```
const cache = require('cache-all')

module.exports.update = async function (req, res) {
    try {
        let users = await User.findOne({ USER_ID: req.params.USER_ID });
        await users.set({
            LOGIN: req.body.LOGIN
        })
        users.save().then(function () {
            return cache.set('patch:' + req.params.USER_ID, users);
        }).then(() => {
            return res.status(200).json(users);
        })
    } catch (e) {
        errorHandler(res, e);
    }
};

```

**Comment by bahung1221** [comment]
Hi vibav,

Sorry for the lack,
In this case, you want to manual clear cache of specific middleware, right?
I will implement it tonight, i think it will be `cache.removeMiddleware(req)`.

For now, you can use `cache.clear()` to clear all cache (just a workarought before tonight).

Best regards.

**Comment by bahung1221** [comment]
Hi @vibav ,

New version was publish to npm,
So if you still using this package, please update to version 1.1.1.

I added `cache.removeByPattern` method and add `prefix` argument to `cache.middleware` method, please check this example to fix your issue [example](https://github.com/bahung1221/cache-all/blob/master/example/app.js).

Best regrads.
